---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.14.0
  name: horizontests.test.openstack.org
spec:
  group: test.openstack.org
  names:
    kind: HorizonTest
    listKind: HorizonTestList
    plural: horizontests
    singular: horizontest
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Status
      jsonPath: .status.conditions[0].status
      name: Status
      type: string
    - description: Message
      jsonPath: .status.conditions[0].message
      name: Message
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: HorizonTestSpec defines the desired state of HorizonTest
            properties:
              SELinuxLevel:
                default: ""
                description: |-
                  A SELinuxLevel that should be used for test pods spawned by the test
                  operator.
                type: string
              adminPassword:
                default: admin
                description: AdminPassword is the password for the OpenStack admin
                  user.
                type: string
              adminUsername:
                default: admin
                description: AdminUsername is the username for the OpenStack admin
                  user.
                type: string
              authUrl:
                description: AuthUrl is the authentication URL for OpenStack.
                type: string
              backoffLimit:
                default: 0
                description: BackoffLimit allows to define the maximum number of retried
                  executions (defaults to 0).
                format: int32
                type: integer
              containerImage:
                default: ""
                description: A URL of a container image that should be used by the
                  test-operator for tests execution.
                type: string
              dashboardUrl:
                description: DashboardUrl is the URL of the Horizon dashboard.
                type: string
              debug:
                default: false
                description: |-
                  Activate debug mode. When debug mode is activated any error encountered
                  inside the test-pod causes that the pod will be kept alive indefinitely
                  (stuck in "Running" phase) or until the corresponding HorizonTest CR is deleted.
                  This allows the user to debug any potential troubles with `oc rsh`.
                type: boolean
              extraConfigmapsMounts:
                description: Extra configmaps for mounting inside the pod
                items:
                  properties:
                    mountPath:
                      description: Path within the container at which the volume should
                        be mounted.
                      type: string
                    name:
                      description: The name of an existing config map for mounting.
                      maxLength: 253
                      type: string
                    subPath:
                      default: ""
                      description: Config map subpath for mounting, defaults to configmap
                        root.
                      type: string
                  required:
                  - mountPath
                  - name
                  - subPath
                  type: object
                type: array
              flavorName:
                default: m1.tiny
                description: FlavorName is the name of the OpenStack flavor to create
                  for Horizon tests.
                type: string
              horizonRepoBranch:
                default: master
                description: HorizonRepoBranch is the branch of the Horizon repository
                  to checkout.
                type: string
              horizonTestDir:
                default: /var/lib/horizontest
                description: HorizonTestDir is the directory path for Horizon tests.
                type: string
              imageUrl:
                default: http://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img
                description: ImageUrl is the URL to download the Cirros image.
                type: string
              kubeconfigSecretName:
                description: |-
                  Name of a secret that contains a kubeconfig. The kubeconfig is mounted under /var/lib/horizontest/.kube/config
                  in the test pod.
                type: string
              logsDirectoryName:
                default: horizon
                description: LogsDirectoryName is the name of the directory to store
                  test logs.
                type: string
              nodeSelector:
                additionalProperties:
                  type: string
                description: |-
                  This value contains a nodeSelector value that is applied to test pods
                  spawned by the test operator.
                type: object
              parallel:
                default: false
                description: Parallel
                type: boolean
              password:
                default: horizontest
                description: Password is the password for the user running the Horizon
                  tests.
                type: string
              privileged:
                default: false
                description: |-
                  Use with caution! This parameter specifies whether test-operator should spawn
                  test pods with allowedPrivilegedEscalation: true, readOnlyRootFilesystem: false,
                  runAsNonRoot: false, automountServiceAccountToken: true, and the default
                  capabilities on top of capabilities that are usually needed by the test
                  pods (NET_ADMIN, NET_RAW). This parameter is deemed insecure but it is
                  needed for certain test-operator functionalities to work properly (e.g.:
                  extraRPMs in Tempest CR, or certain set of tobiko tests).
                type: boolean
              projectName:
                default: horizontest
                description: ProjectName is the name of the OpenStack project for
                  Horizon tests.
                type: string
              repoUrl:
                default: https://review.opendev.org/openstack/horizon
                description: RepoUrl is the URL of the Horizon repository.
                type: string
              storageClass:
                default: local-storage
                description: StorageClass used to create any test-operator related
                  PVCs.
                type: string
              tolerations:
                description: |-
                  This value contains a toleration that is applied to pods spawned by the
                  test pods that are spawned by the test-operator.
                items:
                  description: |-
                    The pod this Toleration is attached to tolerates any taint that matches
                    the triple <key,value,effect> using the matching operator <operator>.
                  properties:
                    effect:
                      description: |-
                        Effect indicates the taint effect to match. Empty means match all taint effects.
                        When specified, allowed values are NoSchedule, PreferNoSchedule and NoExecute.
                      type: string
                    key:
                      description: |-
                        Key is the taint key that the toleration applies to. Empty means match all taint keys.
                        If the key is empty, operator must be Exists; this combination means to match all values and all keys.
                      type: string
                    operator:
                      description: |-
                        Operator represents a key's relationship to the value.
                        Valid operators are Exists and Equal. Defaults to Equal.
                        Exists is equivalent to wildcard for value, so that a pod can
                        tolerate all taints of a particular category.
                      type: string
                    tolerationSeconds:
                      description: |-
                        TolerationSeconds represents the period of time the toleration (which must be
                        of effect NoExecute, otherwise this field is ignored) tolerates the taint. By default,
                        it is not set, which means tolerate the taint forever (do not evict). Zero and
                        negative values will be treated as 0 (evict immediately) by the system.
                      format: int64
                      type: integer
                    value:
                      description: |-
                        Value is the taint value the toleration matches to.
                        If the operator is Exists, the value should be empty, otherwise just a regular string.
                      type: string
                  type: object
                type: array
              user:
                default: horizontest
                description: User is the username under which the Horizon tests will
                  run.
                type: string
            required:
            - adminPassword
            - adminUsername
            - authUrl
            - dashboardUrl
            - horizonRepoBranch
            - repoUrl
            type: object
          status:
            description: CommonTestStatus defines the observed state of the controller
            properties:
              conditions:
                description: Conditions
                items:
                  description: Condition defines an observation of a API resource
                    operational state.
                  properties:
                    lastTransitionTime:
                      description: |-
                        Last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed. If that is not known, then using the time when
                        the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition.
                      type: string
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase.
                      type: string
                    severity:
                      description: |-
                        Severity provides a classification of Reason code, so the current situation is immediately
                        understandable and could act accordingly.
                        It is meant for situations where Status=False and it should be indicated if it is just
                        informational, warning (next reconciliation might fix it) or an error (e.g. DB create issue
                        and no actions to automatically resolve the issue can/should be done).
                        For conditions where Status=Unknown or Status=True the Severity should be SeverityNone.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase.
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              hash:
                additionalProperties:
                  type: string
                description: Map of hashes to track e.g. job status
                type: object
              networkAttachments:
                additionalProperties:
                  items:
                    type: string
                  type: array
                description: NetworkAttachments status of the deployment pods
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
